# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "UA");
user_pref("browser.search.region", "UA");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150525141253");
user_pref("browser.slowStartup.averageTime", 1542);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20150525141253");
user_pref("browser.startup.homepage_override.mstone", "38.0.5");
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1435236427571");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1435150089508");
user_pref("datareporting.policy.firstRunTime", "1435150027571");
user_pref("datareporting.sessions.current.activeTicks", 19);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 728);
user_pref("datareporting.sessions.current.main", 46);
user_pref("datareporting.sessions.current.sessionRestored", 816);
user_pref("datareporting.sessions.current.startTime", "1435154471506");
user_pref("datareporting.sessions.current.totalTime", 95);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1435150027157,\"a\":6,\"t\":108,\"c\":true,\"m\":31,\"fp\":2021,\"sr\":2314}");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.0.5");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "38.0.5");
user_pref("extensions.lastPlatformVersion", "38.0.5");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.0.5\",\"st\":1433314200135,\"mt\":1433314200093}},\"winreg-app-global\":{\"{D19CA586-DD6C-4a0a-96F8-14644F340D60}\":{\"d\":\"C:\\\\Program Files (x86)\\\\Common Files\\\\McAfee\\\\SystemCore\",\"e\":false,\"v\":\"15.1.0\",\"st\":1417524264816,\"mt\":1417522778893},\"fiddlerhook@fiddler2.com\":{\"d\":\"C:\\\\Program Files (x86)\\\\Fiddler2\\\\FiddlerHook\",\"e\":false,\"v\":\"2.4.9.7\",\"st\":1418804427232,\"mt\":1416625068000}}}");
user_pref("gecko.buildID", "20150525141253");
user_pref("gecko.mstone", "38.0.5");
user_pref("gfx.direct3d.last_used_feature_level_idx", 1);
user_pref("media.gmp-eme-adobe.lastUpdate", 1435150091);
user_pref("media.gmp-eme-adobe.version", "11");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1435150092);
user_pref("media.gmp-gmpopenh264.version", "1.4");
user_pref("media.gmp-manager.buildID", "20150525141253");
user_pref("media.gmp-manager.lastCheck", 1435150090);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("print.always_print_silent", true);
user_pref("print.enable_e10s_testing", false);
user_pref("print.show_print_progress", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1435154471);
user_pref("toolkit.telemetry.previousBuildID", "20150525141253");
